/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * The version of the OpenAPI document: 2.9
 * Contact: support@haproxy.com
 * Generated by: https://openapi-generator.tech
 */

/// AclFile : ACL File



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AclFile {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "storage_name", skip_serializing_if = "Option::is_none")]
    pub storage_name: Option<String>,
}

impl AclFile {
    /// ACL File
    pub fn new() -> AclFile {
        AclFile {
            description: None,
            id: None,
            storage_name: None,
        }
    }
}


