/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * The version of the OpenAPI document: 2.9
 * Contact: support@haproxy.com
 * Generated by: https://openapi-generator.tech
 */

/// Backend : HAProxy backend configuration



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Backend {
    #[serde(rename = "abortonclose", skip_serializing_if = "Option::is_none")]
    pub abortonclose: Option<Abortonclose>,
    #[serde(rename = "accept_invalid_http_response", skip_serializing_if = "Option::is_none")]
    pub accept_invalid_http_response: Option<AcceptInvalidHttpResponse>,
    #[serde(rename = "adv_check", skip_serializing_if = "Option::is_none")]
    pub adv_check: Option<AdvCheck>,
    #[serde(rename = "allbackups", skip_serializing_if = "Option::is_none")]
    pub allbackups: Option<Allbackups>,
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<Box<crate::models::Balance>>,
    #[serde(rename = "bind_process", skip_serializing_if = "Option::is_none")]
    pub bind_process: Option<String>,
    #[serde(rename = "check_timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub check_timeout: Option<Option<i32>>,
    #[serde(rename = "checkcache", skip_serializing_if = "Option::is_none")]
    pub checkcache: Option<Checkcache>,
    #[serde(rename = "compression", skip_serializing_if = "Option::is_none")]
    pub compression: Option<Box<crate::models::Compression>>,
    #[serde(rename = "connect_timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub connect_timeout: Option<Option<i32>>,
    #[serde(rename = "cookie", skip_serializing_if = "Option::is_none")]
    pub cookie: Option<Box<crate::models::Cookie>>,
    #[serde(rename = "default_server", skip_serializing_if = "Option::is_none")]
    pub default_server: Option<Box<crate::models::DefaultServer>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    #[serde(rename = "dynamic_cookie_key", skip_serializing_if = "Option::is_none")]
    pub dynamic_cookie_key: Option<String>,
    #[serde(rename = "email_alert", skip_serializing_if = "Option::is_none")]
    pub email_alert: Option<Box<crate::models::EmailAlert>>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "error_files", skip_serializing_if = "Option::is_none")]
    pub error_files: Option<Vec<crate::models::Errorfile>>,
    #[serde(rename = "errorfiles_from_http_errors", skip_serializing_if = "Option::is_none")]
    pub errorfiles_from_http_errors: Option<Vec<crate::models::Errorfiles>>,
    #[serde(rename = "errorloc302", skip_serializing_if = "Option::is_none")]
    pub errorloc302: Option<Box<crate::models::Errorloc>>,
    #[serde(rename = "errorloc303", skip_serializing_if = "Option::is_none")]
    pub errorloc303: Option<Box<crate::models::Errorloc>>,
    #[serde(rename = "external_check", skip_serializing_if = "Option::is_none")]
    pub external_check: Option<ExternalCheck>,
    #[serde(rename = "external_check_command", skip_serializing_if = "Option::is_none")]
    pub external_check_command: Option<String>,
    #[serde(rename = "external_check_path", skip_serializing_if = "Option::is_none")]
    pub external_check_path: Option<String>,
    #[serde(rename = "force_persist", skip_serializing_if = "Option::is_none")]
    pub force_persist: Option<Box<crate::models::BackendForcePersist>>,
    #[serde(rename = "forwardfor", skip_serializing_if = "Option::is_none")]
    pub forwardfor: Option<Box<crate::models::Forwardfor>>,
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    #[serde(rename = "fullconn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fullconn: Option<Option<i32>>,
    #[serde(rename = "h1_case_adjust_bogus_server", skip_serializing_if = "Option::is_none")]
    pub h1_case_adjust_bogus_server: Option<H1CaseAdjustBogusServer>,
    #[serde(rename = "hash_type", skip_serializing_if = "Option::is_none")]
    pub hash_type: Option<Box<crate::models::HashType>>,
    #[serde(rename = "http-buffer-request", skip_serializing_if = "Option::is_none")]
    pub http_buffer_request: Option<HttpBufferRequest>,
    #[serde(rename = "http-check", skip_serializing_if = "Option::is_none")]
    pub http_check: Option<Box<crate::models::HttpCheck>>,
    #[serde(rename = "http-keep-alive", skip_serializing_if = "Option::is_none")]
    pub http_keep_alive: Option<HttpKeepAlive>,
    #[serde(rename = "http-no-delay", skip_serializing_if = "Option::is_none")]
    pub http_no_delay: Option<HttpNoDelay>,
    #[serde(rename = "http-server-close", skip_serializing_if = "Option::is_none")]
    pub http_server_close: Option<HttpServerClose>,
    #[serde(rename = "http-use-htx", skip_serializing_if = "Option::is_none")]
    pub http_use_htx: Option<HttpUseHtx>,
    #[serde(rename = "http_connection_mode", skip_serializing_if = "Option::is_none")]
    pub http_connection_mode: Option<HttpConnectionMode>,
    #[serde(rename = "http_keep_alive_timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub http_keep_alive_timeout: Option<Option<i32>>,
    #[serde(rename = "http_pretend_keepalive", skip_serializing_if = "Option::is_none")]
    pub http_pretend_keepalive: Option<HttpPretendKeepalive>,
    #[serde(rename = "http_proxy", skip_serializing_if = "Option::is_none")]
    pub http_proxy: Option<HttpProxy>,
    #[serde(rename = "http_request_timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub http_request_timeout: Option<Option<i32>>,
    #[serde(rename = "http_restrict_req_hdr_names", skip_serializing_if = "Option::is_none")]
    pub http_restrict_req_hdr_names: Option<HttpRestrictReqHdrNames>,
    #[serde(rename = "http_reuse", skip_serializing_if = "Option::is_none")]
    pub http_reuse: Option<HttpReuse>,
    #[serde(rename = "http_send_name_header", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub http_send_name_header: Option<Option<String>>,
    #[serde(rename = "httpchk_params", skip_serializing_if = "Option::is_none")]
    pub httpchk_params: Option<Box<crate::models::HttpchkParams>>,
    #[serde(rename = "httpclose", skip_serializing_if = "Option::is_none")]
    pub httpclose: Option<Httpclose>,
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<i32>>,
    #[serde(rename = "ignore_persist", skip_serializing_if = "Option::is_none")]
    pub ignore_persist: Option<Box<crate::models::BackendForcePersist>>,
    #[serde(rename = "independent_streams", skip_serializing_if = "Option::is_none")]
    pub independent_streams: Option<IndependentStreams>,
    #[serde(rename = "load_server_state_from_file", skip_serializing_if = "Option::is_none")]
    pub load_server_state_from_file: Option<LoadServerStateFromFile>,
    #[serde(rename = "log_health_checks", skip_serializing_if = "Option::is_none")]
    pub log_health_checks: Option<LogHealthChecks>,
    #[serde(rename = "log_tag", skip_serializing_if = "Option::is_none")]
    pub log_tag: Option<String>,
    #[serde(rename = "max_keep_alive_queue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_keep_alive_queue: Option<Option<i32>>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
    #[serde(rename = "mysql_check_params", skip_serializing_if = "Option::is_none")]
    pub mysql_check_params: Option<Box<crate::models::MysqlCheckParams>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "nolinger", skip_serializing_if = "Option::is_none")]
    pub nolinger: Option<Nolinger>,
    #[serde(rename = "originalto", skip_serializing_if = "Option::is_none")]
    pub originalto: Option<Box<crate::models::Originalto>>,
    #[serde(rename = "persist", skip_serializing_if = "Option::is_none")]
    pub persist: Option<Persist>,
    #[serde(rename = "persist_rule", skip_serializing_if = "Option::is_none")]
    pub persist_rule: Option<Box<crate::models::PersistRule>>,
    #[serde(rename = "pgsql_check_params", skip_serializing_if = "Option::is_none")]
    pub pgsql_check_params: Option<Box<crate::models::PgsqlCheckParams>>,
    #[serde(rename = "prefer_last_server", skip_serializing_if = "Option::is_none")]
    pub prefer_last_server: Option<PreferLastServer>,
    #[serde(rename = "queue_timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub queue_timeout: Option<Option<i32>>,
    #[serde(rename = "redispatch", skip_serializing_if = "Option::is_none")]
    pub redispatch: Option<Box<crate::models::Redispatch>>,
    #[serde(rename = "retries", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub retries: Option<Option<i32>>,
    #[serde(rename = "retry_on", skip_serializing_if = "Option::is_none")]
    pub retry_on: Option<String>,
    #[serde(rename = "server_fin_timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub server_fin_timeout: Option<Option<i32>>,
    #[serde(rename = "server_state_file_name", skip_serializing_if = "Option::is_none")]
    pub server_state_file_name: Option<String>,
    #[serde(rename = "server_timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub server_timeout: Option<Option<i32>>,
    #[serde(rename = "smtpchk_params", skip_serializing_if = "Option::is_none")]
    pub smtpchk_params: Option<Box<crate::models::SmtpchkParams>>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<crate::models::Source>>,
    #[serde(rename = "splice_auto", skip_serializing_if = "Option::is_none")]
    pub splice_auto: Option<SpliceAuto>,
    #[serde(rename = "splice_request", skip_serializing_if = "Option::is_none")]
    pub splice_request: Option<SpliceRequest>,
    #[serde(rename = "splice_response", skip_serializing_if = "Option::is_none")]
    pub splice_response: Option<SpliceResponse>,
    #[serde(rename = "spop_check", skip_serializing_if = "Option::is_none")]
    pub spop_check: Option<SpopCheck>,
    #[serde(rename = "srvtcpka", skip_serializing_if = "Option::is_none")]
    pub srvtcpka: Option<Srvtcpka>,
    #[serde(rename = "srvtcpka_cnt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub srvtcpka_cnt: Option<Option<i32>>,
    #[serde(rename = "srvtcpka_idle", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub srvtcpka_idle: Option<Option<i32>>,
    #[serde(rename = "srvtcpka_intvl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub srvtcpka_intvl: Option<Option<i32>>,
    #[serde(rename = "stats_options", skip_serializing_if = "Option::is_none")]
    pub stats_options: Option<Box<crate::models::StatsOptions>>,
    #[serde(rename = "stick_table", skip_serializing_if = "Option::is_none")]
    pub stick_table: Option<Box<crate::models::ConfigStickTable>>,
    #[serde(rename = "tarpit_timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tarpit_timeout: Option<Option<i32>>,
    #[serde(rename = "tcp_smart_connect", skip_serializing_if = "Option::is_none")]
    pub tcp_smart_connect: Option<TcpSmartConnect>,
    #[serde(rename = "tcpka", skip_serializing_if = "Option::is_none")]
    pub tcpka: Option<Tcpka>,
    #[serde(rename = "transparent", skip_serializing_if = "Option::is_none")]
    pub transparent: Option<Transparent>,
    #[serde(rename = "tunnel_timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tunnel_timeout: Option<Option<i32>>,
    #[serde(rename = "use_fcgi_app", skip_serializing_if = "Option::is_none")]
    pub use_fcgi_app: Option<String>,
}

impl Backend {
    /// HAProxy backend configuration
    pub fn new(name: String) -> Backend {
        Backend {
            abortonclose: None,
            accept_invalid_http_response: None,
            adv_check: None,
            allbackups: None,
            balance: None,
            bind_process: None,
            check_timeout: None,
            checkcache: None,
            compression: None,
            connect_timeout: None,
            cookie: None,
            default_server: None,
            description: None,
            disabled: None,
            dynamic_cookie_key: None,
            email_alert: None,
            enabled: None,
            error_files: None,
            errorfiles_from_http_errors: None,
            errorloc302: None,
            errorloc303: None,
            external_check: None,
            external_check_command: None,
            external_check_path: None,
            force_persist: None,
            forwardfor: None,
            from: None,
            fullconn: None,
            h1_case_adjust_bogus_server: None,
            hash_type: None,
            http_buffer_request: None,
            http_check: None,
            http_keep_alive: None,
            http_no_delay: None,
            http_server_close: None,
            http_use_htx: None,
            http_connection_mode: None,
            http_keep_alive_timeout: None,
            http_pretend_keepalive: None,
            http_proxy: None,
            http_request_timeout: None,
            http_restrict_req_hdr_names: None,
            http_reuse: None,
            http_send_name_header: None,
            httpchk_params: None,
            httpclose: None,
            id: None,
            ignore_persist: None,
            independent_streams: None,
            load_server_state_from_file: None,
            log_health_checks: None,
            log_tag: None,
            max_keep_alive_queue: None,
            mode: None,
            mysql_check_params: None,
            name,
            nolinger: None,
            originalto: None,
            persist: None,
            persist_rule: None,
            pgsql_check_params: None,
            prefer_last_server: None,
            queue_timeout: None,
            redispatch: None,
            retries: None,
            retry_on: None,
            server_fin_timeout: None,
            server_state_file_name: None,
            server_timeout: None,
            smtpchk_params: None,
            source: None,
            splice_auto: None,
            splice_request: None,
            splice_response: None,
            spop_check: None,
            srvtcpka: None,
            srvtcpka_cnt: None,
            srvtcpka_idle: None,
            srvtcpka_intvl: None,
            stats_options: None,
            stick_table: None,
            tarpit_timeout: None,
            tcp_smart_connect: None,
            tcpka: None,
            transparent: None,
            tunnel_timeout: None,
            use_fcgi_app: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Abortonclose {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Abortonclose {
    fn default() -> Abortonclose {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AcceptInvalidHttpResponse {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for AcceptInvalidHttpResponse {
    fn default() -> AcceptInvalidHttpResponse {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AdvCheck {
    #[serde(rename = "ssl-hello-chk")]
    SslHelloChk,
    #[serde(rename = "smtpchk")]
    Smtpchk,
    #[serde(rename = "ldap-check")]
    LdapCheck,
    #[serde(rename = "mysql-check")]
    MysqlCheck,
    #[serde(rename = "pgsql-check")]
    PgsqlCheck,
    #[serde(rename = "tcp-check")]
    TcpCheck,
    #[serde(rename = "redis-check")]
    RedisCheck,
    #[serde(rename = "httpchk")]
    Httpchk,
}

impl Default for AdvCheck {
    fn default() -> AdvCheck {
        Self::SslHelloChk
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Allbackups {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Allbackups {
    fn default() -> Allbackups {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Checkcache {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Checkcache {
    fn default() -> Checkcache {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExternalCheck {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for ExternalCheck {
    fn default() -> ExternalCheck {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum H1CaseAdjustBogusServer {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for H1CaseAdjustBogusServer {
    fn default() -> H1CaseAdjustBogusServer {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpBufferRequest {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for HttpBufferRequest {
    fn default() -> HttpBufferRequest {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpKeepAlive {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for HttpKeepAlive {
    fn default() -> HttpKeepAlive {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpNoDelay {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for HttpNoDelay {
    fn default() -> HttpNoDelay {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpServerClose {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for HttpServerClose {
    fn default() -> HttpServerClose {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpUseHtx {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for HttpUseHtx {
    fn default() -> HttpUseHtx {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpConnectionMode {
    #[serde(rename = "httpclose")]
    Httpclose,
    #[serde(rename = "http-server-close")]
    HttpServerClose,
    #[serde(rename = "http-keep-alive")]
    HttpKeepAlive,
}

impl Default for HttpConnectionMode {
    fn default() -> HttpConnectionMode {
        Self::Httpclose
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpPretendKeepalive {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for HttpPretendKeepalive {
    fn default() -> HttpPretendKeepalive {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpProxy {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for HttpProxy {
    fn default() -> HttpProxy {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpRestrictReqHdrNames {
    #[serde(rename = "preserve")]
    Preserve,
    #[serde(rename = "delete")]
    Delete,
    #[serde(rename = "reject")]
    Reject,
}

impl Default for HttpRestrictReqHdrNames {
    fn default() -> HttpRestrictReqHdrNames {
        Self::Preserve
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpReuse {
    #[serde(rename = "aggressive")]
    Aggressive,
    #[serde(rename = "always")]
    Always,
    #[serde(rename = "never")]
    Never,
    #[serde(rename = "safe")]
    Safe,
}

impl Default for HttpReuse {
    fn default() -> HttpReuse {
        Self::Aggressive
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Httpclose {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Httpclose {
    fn default() -> Httpclose {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IndependentStreams {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for IndependentStreams {
    fn default() -> IndependentStreams {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LoadServerStateFromFile {
    #[serde(rename = "global")]
    Global,
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "none")]
    None,
}

impl Default for LoadServerStateFromFile {
    fn default() -> LoadServerStateFromFile {
        Self::Global
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogHealthChecks {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for LogHealthChecks {
    fn default() -> LogHealthChecks {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "http")]
    Http,
    #[serde(rename = "tcp")]
    Tcp,
    #[serde(rename = "log")]
    Log,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Http
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Nolinger {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Nolinger {
    fn default() -> Nolinger {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Persist {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Persist {
    fn default() -> Persist {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PreferLastServer {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for PreferLastServer {
    fn default() -> PreferLastServer {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpliceAuto {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for SpliceAuto {
    fn default() -> SpliceAuto {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpliceRequest {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for SpliceRequest {
    fn default() -> SpliceRequest {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpliceResponse {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for SpliceResponse {
    fn default() -> SpliceResponse {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpopCheck {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for SpopCheck {
    fn default() -> SpopCheck {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Srvtcpka {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Srvtcpka {
    fn default() -> Srvtcpka {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TcpSmartConnect {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for TcpSmartConnect {
    fn default() -> TcpSmartConnect {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Tcpka {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Tcpka {
    fn default() -> Tcpka {
        Self::Enabled
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Transparent {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Transparent {
    fn default() -> Transparent {
        Self::Enabled
    }
}

