/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * The version of the OpenAPI document: 2.9
 * Contact: support@haproxy.com
 * Generated by: https://openapi-generator.tech
 */

/// Cache : HAPRoxy Cache section



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Cache {
    #[serde(rename = "max_age", skip_serializing_if = "Option::is_none")]
    pub max_age: Option<i32>,
    #[serde(rename = "max_object_size", skip_serializing_if = "Option::is_none")]
    pub max_object_size: Option<i32>,
    #[serde(rename = "max_secondary_entries", skip_serializing_if = "Option::is_none")]
    pub max_secondary_entries: Option<i32>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "process_vary", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub process_vary: Option<Option<bool>>,
    #[serde(rename = "total_max_size", skip_serializing_if = "Option::is_none")]
    pub total_max_size: Option<i32>,
}

impl Cache {
    /// HAPRoxy Cache section
    pub fn new(name: String) -> Cache {
        Cache {
            max_age: None,
            max_object_size: None,
            max_secondary_entries: None,
            name,
            process_vary: None,
            total_max_size: None,
        }
    }
}


