/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.
 *
 * The version of the OpenAPI document: 2.9
 * Contact: support@haproxy.com
 * Generated by: https://openapi-generator.tech
 */

/// Frontend : HAProxy frontend configuration

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Frontend {
    #[serde(
        rename = "accept_invalid_http_request",
        skip_serializing_if = "Option::is_none"
    )]
    pub accept_invalid_http_request: Option<AcceptInvalidHttpRequest>,
    #[serde(
        rename = "backlog",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub backlog: Option<Option<i32>>,
    #[serde(rename = "bind_process", skip_serializing_if = "Option::is_none")]
    pub bind_process: Option<String>,
    #[serde(rename = "clflog", skip_serializing_if = "Option::is_none")]
    pub clflog: Option<bool>,
    #[serde(
        rename = "client_fin_timeout",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub client_fin_timeout: Option<Option<i32>>,
    #[serde(
        rename = "client_timeout",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub client_timeout: Option<Option<i32>>,
    #[serde(rename = "clitcpka", skip_serializing_if = "Option::is_none")]
    pub clitcpka: Option<Clitcpka>,
    #[serde(
        rename = "clitcpka_cnt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub clitcpka_cnt: Option<Option<i32>>,
    #[serde(
        rename = "clitcpka_idle",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub clitcpka_idle: Option<Option<i32>>,
    #[serde(
        rename = "clitcpka_intvl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub clitcpka_intvl: Option<Option<i32>>,
    #[serde(rename = "compression", skip_serializing_if = "Option::is_none")]
    pub compression: Option<Box<crate::models::Compression>>,
    #[serde(rename = "contstats", skip_serializing_if = "Option::is_none")]
    pub contstats: Option<Contstats>,
    #[serde(rename = "default_backend", skip_serializing_if = "Option::is_none")]
    pub default_backend: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "disable_h2_upgrade", skip_serializing_if = "Option::is_none")]
    pub disable_h2_upgrade: Option<DisableH2Upgrade>,
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    #[serde(rename = "dontlog_normal", skip_serializing_if = "Option::is_none")]
    pub dontlog_normal: Option<DontlogNormal>,
    #[serde(rename = "dontlognull", skip_serializing_if = "Option::is_none")]
    pub dontlognull: Option<Dontlognull>,
    #[serde(rename = "email_alert", skip_serializing_if = "Option::is_none")]
    pub email_alert: Option<Box<crate::models::EmailAlert>>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "error_files", skip_serializing_if = "Option::is_none")]
    pub error_files: Option<Vec<crate::models::Errorfile>>,
    #[serde(rename = "error_log_format", skip_serializing_if = "Option::is_none")]
    pub error_log_format: Option<String>,
    #[serde(
        rename = "errorfiles_from_http_errors",
        skip_serializing_if = "Option::is_none"
    )]
    pub errorfiles_from_http_errors: Option<Vec<crate::models::Errorfiles>>,
    #[serde(rename = "errorloc302", skip_serializing_if = "Option::is_none")]
    pub errorloc302: Option<Box<crate::models::Errorloc>>,
    #[serde(rename = "errorloc303", skip_serializing_if = "Option::is_none")]
    pub errorloc303: Option<Box<crate::models::Errorloc>>,
    #[serde(rename = "forwardfor", skip_serializing_if = "Option::is_none")]
    pub forwardfor: Option<Box<crate::models::Forwardfor>>,
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    #[serde(
        rename = "h1_case_adjust_bogus_client",
        skip_serializing_if = "Option::is_none"
    )]
    pub h1_case_adjust_bogus_client: Option<H1CaseAdjustBogusClient>,
    #[serde(
        rename = "http-buffer-request",
        skip_serializing_if = "Option::is_none"
    )]
    pub http_buffer_request: Option<HttpBufferRequest>,
    #[serde(rename = "http-use-htx", skip_serializing_if = "Option::is_none")]
    pub http_use_htx: Option<HttpUseHtx>,
    #[serde(
        rename = "http_connection_mode",
        skip_serializing_if = "Option::is_none"
    )]
    pub http_connection_mode: Option<HttpConnectionMode>,
    #[serde(rename = "http_ignore_probes", skip_serializing_if = "Option::is_none")]
    pub http_ignore_probes: Option<HttpIgnoreProbes>,
    #[serde(
        rename = "http_keep_alive_timeout",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub http_keep_alive_timeout: Option<Option<i32>>,
    #[serde(rename = "http_no_delay", skip_serializing_if = "Option::is_none")]
    pub http_no_delay: Option<HttpNoDelay>,
    #[serde(
        rename = "http_request_timeout",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub http_request_timeout: Option<Option<i32>>,
    #[serde(
        rename = "http_restrict_req_hdr_names",
        skip_serializing_if = "Option::is_none"
    )]
    pub http_restrict_req_hdr_names: Option<HttpRestrictReqHdrNames>,
    #[serde(
        rename = "http_use_proxy_header",
        skip_serializing_if = "Option::is_none"
    )]
    pub http_use_proxy_header: Option<HttpUseProxyHeader>,
    #[serde(rename = "httplog", skip_serializing_if = "Option::is_none")]
    pub httplog: Option<bool>,
    #[serde(rename = "httpslog", skip_serializing_if = "Option::is_none")]
    pub httpslog: Option<Httpslog>,
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<i32>>,
    #[serde(
        rename = "idle_close_on_response",
        skip_serializing_if = "Option::is_none"
    )]
    pub idle_close_on_response: Option<IdleCloseOnResponse>,
    #[serde(
        rename = "independent_streams",
        skip_serializing_if = "Option::is_none"
    )]
    pub independent_streams: Option<IndependentStreams>,
    #[serde(rename = "log_format", skip_serializing_if = "Option::is_none")]
    pub log_format: Option<String>,
    #[serde(rename = "log_format_sd", skip_serializing_if = "Option::is_none")]
    pub log_format_sd: Option<String>,
    #[serde(
        rename = "log_separate_errors",
        skip_serializing_if = "Option::is_none"
    )]
    pub log_separate_errors: Option<LogSeparateErrors>,
    #[serde(rename = "log_tag", skip_serializing_if = "Option::is_none")]
    pub log_tag: Option<String>,
    #[serde(rename = "logasap", skip_serializing_if = "Option::is_none")]
    pub logasap: Option<Logasap>,
    #[serde(
        rename = "maxconn",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub maxconn: Option<Option<i32>>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
    #[serde(rename = "monitor_fail", skip_serializing_if = "Option::is_none")]
    pub monitor_fail: Option<Box<crate::models::MonitorFail>>,
    #[serde(rename = "monitor_uri", skip_serializing_if = "Option::is_none")]
    pub monitor_uri: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "nolinger", skip_serializing_if = "Option::is_none")]
    pub nolinger: Option<Nolinger>,
    #[serde(rename = "originalto", skip_serializing_if = "Option::is_none")]
    pub originalto: Option<Box<crate::models::Originalto>>,
    #[serde(rename = "socket_stats", skip_serializing_if = "Option::is_none")]
    pub socket_stats: Option<SocketStats>,
    #[serde(rename = "splice_auto", skip_serializing_if = "Option::is_none")]
    pub splice_auto: Option<SpliceAuto>,
    #[serde(rename = "splice_request", skip_serializing_if = "Option::is_none")]
    pub splice_request: Option<SpliceRequest>,
    #[serde(rename = "splice_response", skip_serializing_if = "Option::is_none")]
    pub splice_response: Option<SpliceResponse>,
    #[serde(rename = "stats_options", skip_serializing_if = "Option::is_none")]
    pub stats_options: Option<Box<crate::models::StatsOptions>>,
    #[serde(rename = "stick_table", skip_serializing_if = "Option::is_none")]
    pub stick_table: Option<Box<crate::models::ConfigStickTable>>,
    #[serde(
        rename = "tarpit_timeout",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tarpit_timeout: Option<Option<i32>>,
    #[serde(rename = "tcp_smart_accept", skip_serializing_if = "Option::is_none")]
    pub tcp_smart_accept: Option<TcpSmartAccept>,
    #[serde(rename = "tcpka", skip_serializing_if = "Option::is_none")]
    pub tcpka: Option<Tcpka>,
    #[serde(rename = "tcplog", skip_serializing_if = "Option::is_none")]
    pub tcplog: Option<bool>,
    #[serde(rename = "unique_id_format", skip_serializing_if = "Option::is_none")]
    pub unique_id_format: Option<String>,
    #[serde(rename = "unique_id_header", skip_serializing_if = "Option::is_none")]
    pub unique_id_header: Option<String>,
}

impl Frontend {
    /// HAProxy frontend configuration
    pub fn new(name: String) -> Frontend {
        Frontend {
            accept_invalid_http_request: None,
            backlog: None,
            bind_process: None,
            clflog: None,
            client_fin_timeout: None,
            client_timeout: None,
            clitcpka: None,
            clitcpka_cnt: None,
            clitcpka_idle: None,
            clitcpka_intvl: None,
            compression: None,
            contstats: None,
            default_backend: None,
            description: None,
            disable_h2_upgrade: None,
            disabled: None,
            dontlog_normal: None,
            dontlognull: None,
            email_alert: None,
            enabled: None,
            error_files: None,
            error_log_format: None,
            errorfiles_from_http_errors: None,
            errorloc302: None,
            errorloc303: None,
            forwardfor: None,
            from: None,
            h1_case_adjust_bogus_client: None,
            http_buffer_request: None,
            http_use_htx: None,
            http_connection_mode: None,
            http_ignore_probes: None,
            http_keep_alive_timeout: None,
            http_no_delay: None,
            http_request_timeout: None,
            http_restrict_req_hdr_names: None,
            http_use_proxy_header: None,
            httplog: None,
            httpslog: None,
            id: None,
            idle_close_on_response: None,
            independent_streams: None,
            log_format: None,
            log_format_sd: None,
            log_separate_errors: None,
            log_tag: None,
            logasap: None,
            maxconn: None,
            mode: None,
            monitor_fail: None,
            monitor_uri: None,
            name,
            nolinger: None,
            originalto: None,
            socket_stats: None,
            splice_auto: None,
            splice_request: None,
            splice_response: None,
            stats_options: None,
            stick_table: None,
            tarpit_timeout: None,
            tcp_smart_accept: None,
            tcpka: None,
            tcplog: None,
            unique_id_format: None,
            unique_id_header: None,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AcceptInvalidHttpRequest {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for AcceptInvalidHttpRequest {
    fn default() -> AcceptInvalidHttpRequest {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Clitcpka {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Clitcpka {
    fn default() -> Clitcpka {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Contstats {
    #[serde(rename = "enabled")]
    Enabled,
}

impl Default for Contstats {
    fn default() -> Contstats {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DisableH2Upgrade {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for DisableH2Upgrade {
    fn default() -> DisableH2Upgrade {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DontlogNormal {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for DontlogNormal {
    fn default() -> DontlogNormal {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Dontlognull {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Dontlognull {
    fn default() -> Dontlognull {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum H1CaseAdjustBogusClient {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for H1CaseAdjustBogusClient {
    fn default() -> H1CaseAdjustBogusClient {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpBufferRequest {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for HttpBufferRequest {
    fn default() -> HttpBufferRequest {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpUseHtx {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for HttpUseHtx {
    fn default() -> HttpUseHtx {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpConnectionMode {
    #[serde(rename = "httpclose")]
    Httpclose,
    #[serde(rename = "http-server-close")]
    HttpServerClose,
    #[serde(rename = "http-keep-alive")]
    HttpKeepAlive,
}

impl Default for HttpConnectionMode {
    fn default() -> HttpConnectionMode {
        Self::Httpclose
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpIgnoreProbes {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for HttpIgnoreProbes {
    fn default() -> HttpIgnoreProbes {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpNoDelay {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for HttpNoDelay {
    fn default() -> HttpNoDelay {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpRestrictReqHdrNames {
    #[serde(rename = "preserve")]
    Preserve,
    #[serde(rename = "delete")]
    Delete,
    #[serde(rename = "reject")]
    Reject,
}

impl Default for HttpRestrictReqHdrNames {
    fn default() -> HttpRestrictReqHdrNames {
        Self::Preserve
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HttpUseProxyHeader {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for HttpUseProxyHeader {
    fn default() -> HttpUseProxyHeader {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Httpslog {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Httpslog {
    fn default() -> Httpslog {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IdleCloseOnResponse {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for IdleCloseOnResponse {
    fn default() -> IdleCloseOnResponse {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IndependentStreams {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for IndependentStreams {
    fn default() -> IndependentStreams {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogSeparateErrors {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for LogSeparateErrors {
    fn default() -> LogSeparateErrors {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Logasap {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Logasap {
    fn default() -> Logasap {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "http")]
    Http,
    #[serde(rename = "tcp")]
    Tcp,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Http
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Nolinger {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Nolinger {
    fn default() -> Nolinger {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SocketStats {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for SocketStats {
    fn default() -> SocketStats {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpliceAuto {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for SpliceAuto {
    fn default() -> SpliceAuto {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpliceRequest {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for SpliceRequest {
    fn default() -> SpliceRequest {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpliceResponse {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for SpliceResponse {
    fn default() -> SpliceResponse {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TcpSmartAccept {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for TcpSmartAccept {
    fn default() -> TcpSmartAccept {
        Self::Enabled
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Tcpka {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Tcpka {
    fn default() -> Tcpka {
        Self::Enabled
    }
}
