/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * The version of the OpenAPI document: 2.9
 * Contact: support@haproxy.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GlobalDefaultPath {
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl GlobalDefaultPath {
    pub fn new(r#type: Type) -> GlobalDefaultPath {
        GlobalDefaultPath {
            path: None,
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "current")]
    Current,
    #[serde(rename = "config")]
    Config,
    #[serde(rename = "parent")]
    Parent,
    #[serde(rename = "origin")]
    Origin,
}

impl Default for Type {
    fn default() -> Type {
        Self::Current
    }
}

