/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * The version of the OpenAPI document: 2.9
 * Contact: support@haproxy.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Default, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GlobalLuaPrependPathInner {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl GlobalLuaPrependPathInner {
    pub fn new(path: String) -> GlobalLuaPrependPathInner {
        GlobalLuaPrependPathInner {
            path,
            r#type: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "path")]
    Path,
    #[serde(rename = "cpath")]
    Cpath,
}

impl Default for Type {
    fn default() -> Type {
        Self::Path
    }
}

