/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * The version of the OpenAPI document: 2.9
 * Contact: support@haproxy.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GlobalSslEnginesInner {
    #[serde(rename = "algorithms", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub algorithms: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
}

impl GlobalSslEnginesInner {
    pub fn new(name: String) -> GlobalSslEnginesInner {
        GlobalSslEnginesInner {
            algorithms: None,
            name,
        }
    }
}


