/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * The version of the OpenAPI document: 2.9
 * Contact: support@haproxy.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Default, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HashType {
    #[serde(rename = "function", skip_serializing_if = "Option::is_none")]
    pub function: Option<Function>,
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<Method>,
    #[serde(rename = "modifier", skip_serializing_if = "Option::is_none")]
    pub modifier: Option<Modifier>,
}

impl HashType {
    pub fn new() -> HashType {
        HashType {
            function: None,
            method: None,
            modifier: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Function {
    #[serde(rename = "sdbm")]
    Sdbm,
    #[serde(rename = "djb2")]
    Djb2,
    #[serde(rename = "wt6")]
    Wt6,
    #[serde(rename = "crc32")]
    Crc32,
    #[serde(rename = "none")]
    None,
}

impl Default for Function {
    fn default() -> Function {
        Self::Sdbm
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Method {
    #[serde(rename = "map-based")]
    MapBased,
    #[serde(rename = "consistent")]
    Consistent,
}

impl Default for Method {
    fn default() -> Method {
        Self::MapBased
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Modifier {
    #[serde(rename = "avalanche")]
    Avalanche,
}

impl Default for Modifier {
    fn default() -> Modifier {
        Self::Avalanche
    }
}

