/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * The version of the OpenAPI document: 2.9
 * Contact: support@haproxy.com
 * Generated by: https://openapi-generator.tech
 */

/// Info : General API, OS and hardware information



#[derive(Default, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Info {
    #[serde(rename = "api", skip_serializing_if = "Option::is_none")]
    pub api: Option<Box<crate::models::InfoApi>>,
    #[serde(rename = "system", skip_serializing_if = "Option::is_none")]
    pub system: Option<Box<crate::models::InfoSystem>>,
}

impl Info {
    /// General API, OS and hardware information
    pub fn new() -> Info {
        Info {
            api: None,
            system: None,
        }
    }
}


