/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * The version of the OpenAPI document: 2.9
 * Contact: support@haproxy.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Default, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SmtpchkParams {
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(rename = "hello", skip_serializing_if = "Option::is_none")]
    pub hello: Option<String>,
}

impl SmtpchkParams {
    pub fn new() -> SmtpchkParams {
        SmtpchkParams {
            domain: None,
            hello: None,
        }
    }
}


