/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * The version of the OpenAPI document: 2.9
 * Contact: support@haproxy.com
 * Generated by: https://openapi-generator.tech
 */

/// SslCertificate : A file containing one or more SSL/TLS certificates and keys



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SslCertificate {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "domains", skip_serializing_if = "Option::is_none")]
    pub domains: Option<String>,
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<String>,
    #[serde(rename = "ip_addresses", skip_serializing_if = "Option::is_none")]
    pub ip_addresses: Option<String>,
    #[serde(rename = "issuers", skip_serializing_if = "Option::is_none")]
    pub issuers: Option<String>,
    #[serde(rename = "not_after", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub not_after: Option<Option<String>>,
    #[serde(rename = "not_before", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub not_before: Option<Option<String>>,
    /// File size in bytes.
    #[serde(rename = "size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub size: Option<Option<i32>>,
    #[serde(rename = "storage_name", skip_serializing_if = "Option::is_none")]
    pub storage_name: Option<String>,
}

impl SslCertificate {
    /// A file containing one or more SSL/TLS certificates and keys
    pub fn new() -> SslCertificate {
        SslCertificate {
            description: None,
            domains: None,
            file: None,
            ip_addresses: None,
            issuers: None,
            not_after: None,
            not_before: None,
            size: None,
            storage_name: None,
        }
    }
}


