/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * The version of the OpenAPI document: 2.9
 * Contact: support@haproxy.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsAuth {
    #[serde(rename = "passwd")]
    pub passwd: String,
    #[serde(rename = "user")]
    pub user: String,
}

impl StatsAuth {
    pub fn new(passwd: String, user: String) -> StatsAuth {
        StatsAuth {
            passwd,
            user,
        }
    }
}


