/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * The version of the OpenAPI document: 2.9
 * Contact: support@haproxy.com
 * Generated by: https://openapi-generator.tech
 */

/// TcpResponseRule : HAProxy TCP Response Rule configuration (corresponds to tcp-response)



#[derive(Default, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TcpResponseRule {
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<Action>,
    #[serde(rename = "bandwidth_limit_limit", skip_serializing_if = "Option::is_none")]
    pub bandwidth_limit_limit: Option<String>,
    #[serde(rename = "bandwidth_limit_name", skip_serializing_if = "Option::is_none")]
    pub bandwidth_limit_name: Option<String>,
    #[serde(rename = "bandwidth_limit_period", skip_serializing_if = "Option::is_none")]
    pub bandwidth_limit_period: Option<String>,
    #[serde(rename = "cond", skip_serializing_if = "Option::is_none")]
    pub cond: Option<Cond>,
    #[serde(rename = "cond_test", skip_serializing_if = "Option::is_none")]
    pub cond_test: Option<String>,
    #[serde(rename = "expr", skip_serializing_if = "Option::is_none")]
    pub expr: Option<String>,
    #[serde(rename = "index", deserialize_with = "Option::deserialize")]
    pub index: Option<i32>,
    #[serde(rename = "log_level", skip_serializing_if = "Option::is_none")]
    pub log_level: Option<LogLevel>,
    #[serde(rename = "lua_action", skip_serializing_if = "Option::is_none")]
    pub lua_action: Option<String>,
    #[serde(rename = "lua_params", skip_serializing_if = "Option::is_none")]
    pub lua_params: Option<String>,
    #[serde(rename = "mark_value", skip_serializing_if = "Option::is_none")]
    pub mark_value: Option<String>,
    #[serde(rename = "nice_value", skip_serializing_if = "Option::is_none")]
    pub nice_value: Option<i32>,
    #[serde(rename = "sc_expr", skip_serializing_if = "Option::is_none")]
    pub sc_expr: Option<String>,
    #[serde(rename = "sc_id", skip_serializing_if = "Option::is_none")]
    pub sc_id: Option<i32>,
    #[serde(rename = "sc_idx", skip_serializing_if = "Option::is_none")]
    pub sc_idx: Option<i32>,
    #[serde(rename = "sc_int", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sc_int: Option<Option<i32>>,
    #[serde(rename = "spoe_engine", skip_serializing_if = "Option::is_none")]
    pub spoe_engine: Option<String>,
    #[serde(rename = "spoe_group", skip_serializing_if = "Option::is_none")]
    pub spoe_group: Option<String>,
    #[serde(rename = "timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<Option<i32>>,
    #[serde(rename = "tos_value", skip_serializing_if = "Option::is_none")]
    pub tos_value: Option<String>,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "var_name", skip_serializing_if = "Option::is_none")]
    pub var_name: Option<String>,
    #[serde(rename = "var_scope", skip_serializing_if = "Option::is_none")]
    pub var_scope: Option<String>,
}

impl TcpResponseRule {
    /// HAProxy TCP Response Rule configuration (corresponds to tcp-response)
    pub fn new(index: Option<i32>, r#type: Type) -> TcpResponseRule {
        TcpResponseRule {
            action: None,
            bandwidth_limit_limit: None,
            bandwidth_limit_name: None,
            bandwidth_limit_period: None,
            cond: None,
            cond_test: None,
            expr: None,
            index,
            log_level: None,
            lua_action: None,
            lua_params: None,
            mark_value: None,
            nice_value: None,
            sc_expr: None,
            sc_id: None,
            sc_idx: None,
            sc_int: None,
            spoe_engine: None,
            spoe_group: None,
            timeout: None,
            tos_value: None,
            r#type,
            var_name: None,
            var_scope: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "accept")]
    Accept,
    #[serde(rename = "reject")]
    Reject,
    #[serde(rename = "lua")]
    Lua,
    #[serde(rename = "set-bandwidth-limit")]
    SetBandwidthLimit,
    #[serde(rename = "close")]
    Close,
    #[serde(rename = "sc-add-gpc")]
    ScAddGpc,
    #[serde(rename = "sc-inc-gpc")]
    ScIncGpc,
    #[serde(rename = "sc-inc-gpc0")]
    ScIncGpc0,
    #[serde(rename = "sc-inc-gpc1")]
    ScIncGpc1,
    #[serde(rename = "sc-set-gpt0")]
    ScSetGpt0,
    #[serde(rename = "send-spoe-group")]
    SendSpoeGroup,
    #[serde(rename = "set-log-level")]
    SetLogLevel,
    #[serde(rename = "set-mark")]
    SetMark,
    #[serde(rename = "set-nice")]
    SetNice,
    #[serde(rename = "set-tos")]
    SetTos,
    #[serde(rename = "silent-drop")]
    SilentDrop,
    #[serde(rename = "unset-var")]
    UnsetVar,
}

impl Default for Action {
    fn default() -> Action {
        Self::Accept
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Cond {
    #[serde(rename = "if")]
    If,
    #[serde(rename = "unless")]
    Unless,
}

impl Default for Cond {
    fn default() -> Cond {
        Self::If
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogLevel {
    #[serde(rename = "emerg")]
    Emerg,
    #[serde(rename = "alert")]
    Alert,
    #[serde(rename = "crit")]
    Crit,
    #[serde(rename = "err")]
    Err,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "notice")]
    Notice,
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "debug")]
    Debug,
    #[serde(rename = "silent")]
    Silent,
}

impl Default for LogLevel {
    fn default() -> LogLevel {
        Self::Emerg
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "content")]
    Content,
    #[serde(rename = "inspect-delay")]
    InspectDelay,
}

impl Default for Type {
    fn default() -> Type {
        Self::Content
    }
}

